// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDocument(arg1:string):Promise<string>;

export function GetInitialDoc():Promise<string>;

export function GetThemeCSS():Promise<string>;

export function ListDocuments(arg1:string):Promise<Array<main.DocInfo>>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<Array<main.UISearchResult>>;
