// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function GetInitialDoc() {
  return window['go']['main']['App']['GetInitialDoc']();
}

export function GetThemeCSS() {
  return window['go']['main']['App']['GetThemeCSS']();
}

export function ListDocuments(arg1) {
  return window['go']['main']['App']['ListDocuments'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}
